### ISSUE TITLE
Code Improvement

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-booknap#5]
You can just return `a.getCurrency().compareToIgnoreCase(b.getCurrency()`.
compareTo doesn't care whether it is -1 or -2 as long as it is negative number.

https://github.com/OOP2018/coinpurse-booknap/blob/7a8d1f0a08253ce9477fdea5791ea6b56efed455/src/coinpurse/ValueComparator.java#L25-L26

**Comment by bokherus** [comment]
For more info about compareTo of Strings
https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#compareTo(java.lang.String)
